spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://39.106.109.103:3306/homework?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/homework?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates

logging:
  file:
    name: "logs/config/java.log"

# 打印 SQL 日志
 # mybatis.configuration.log-impl = org.apache.ibatis.logging.stdout.StdOutImpl


server:
  #端口号
  port: 80

mybatis:
  type-aliases-package: com.yjg123.projectmanager.domain
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

